// Global country codes with flags and abbreviations
export const COUNTRY_CODES = [
  { code: '+93', country: 'Afghanistan', abbr: 'AF', flag: '🇦🇫' },
  { code: '+355', country: 'Albania', abbr: 'AL', flag: '🇦🇱' },
  { code: '+213', country: 'Algeria', abbr: 'DZ', flag: '🇩🇿' },
  { code: '+1', country: 'United States', abbr: 'US', flag: '🇺🇸' },
  { code: '+376', country: 'Andorra', abbr: 'AD', flag: '🇦🇩' },
  { code: '+244', country: 'Angola', abbr: 'AO', flag: '🇦🇴' },
  { code: '+54', country: 'Argentina', abbr: 'AR', flag: '🇦🇷' },
  { code: '+374', country: 'Armenia', abbr: 'AM', flag: '🇦🇲' },
  { code: '+61', country: 'Australia', abbr: 'AU', flag: '🇦🇺' },
  { code: '+43', country: 'Austria', abbr: 'AT', flag: '🇦🇹' },
  { code: '+994', country: 'Azerbaijan', abbr: 'AZ', flag: '🇦🇿' },
  { code: '+973', country: 'Bahrain', abbr: 'BH', flag: '🇧🇭' },
  { code: '+880', country: 'Bangladesh', abbr: 'BD', flag: '🇧🇩' },
  { code: '+375', country: 'Belarus', abbr: 'BY', flag: '🇧🇾' },
  { code: '+32', country: 'Belgium', abbr: 'BE', flag: '🇧🇪' },
  { code: '+501', country: 'Belize', abbr: 'BZ', flag: '🇧🇿' },
  { code: '+229', country: 'Benin', abbr: 'BJ', flag: '🇧🇯' },
  { code: '+975', country: 'Bhutan', abbr: 'BT', flag: '🇧🇹' },
  { code: '+591', country: 'Bolivia', abbr: 'BO', flag: '🇧🇴' },
  { code: '+387', country: 'Bosnia', abbr: 'BA', flag: '🇧🇦' },
  { code: '+267', country: 'Botswana', abbr: 'BW', flag: '🇧🇼' },
  { code: '+55', country: 'Brazil', abbr: 'BR', flag: '🇧🇷' },
  { code: '+673', country: 'Brunei', abbr: 'BN', flag: '🇧🇳' },
  { code: '+359', country: 'Bulgaria', abbr: 'BG', flag: '🇧🇬' },
  { code: '+226', country: 'Burkina Faso', abbr: 'BF', flag: '🇧🇫' },
  { code: '+257', country: 'Burundi', abbr: 'BI', flag: '🇧🇮' },
  { code: '+855', country: 'Cambodia', abbr: 'KH', flag: '🇰🇭' },
  { code: '+237', country: 'Cameroon', abbr: 'CM', flag: '🇨🇲' },
  { code: '+1', country: 'Canada', abbr: 'CA', flag: '🇨🇦' },
  { code: '+238', country: 'Cape Verde', abbr: 'CV', flag: '🇨🇻' },
  { code: '+236', country: 'Central African Republic', abbr: 'CF', flag: '🇨🇫' },
  { code: '+235', country: 'Chad', abbr: 'TD', flag: '🇹🇩' },
  { code: '+56', country: 'Chile', abbr: 'CL', flag: '🇨🇱' },
  { code: '+86', country: 'China', abbr: 'CN', flag: '🇨🇳' },
  { code: '+57', country: 'Colombia', abbr: 'CO', flag: '🇨🇴' },
  { code: '+269', country: 'Comoros', abbr: 'KM', flag: '🇰🇲' },
  { code: '+242', country: 'Congo', abbr: 'CG', flag: '🇨🇬' },
  { code: '+506', country: 'Costa Rica', abbr: 'CR', flag: '🇨🇷' },
  { code: '+385', country: 'Croatia', abbr: 'HR', flag: '🇭🇷' },
  { code: '+53', country: 'Cuba', abbr: 'CU', flag: '🇨🇺' },
  { code: '+357', country: 'Cyprus', abbr: 'CY', flag: '🇨🇾' },
  { code: '+420', country: 'Czech Republic', abbr: 'CZ', flag: '🇨🇿' },
  { code: '+45', country: 'Denmark', abbr: 'DK', flag: '🇩🇰' },
  { code: '+253', country: 'Djibouti', abbr: 'DJ', flag: '🇩🇯' },
  { code: '+593', country: 'Ecuador', abbr: 'EC', flag: '🇪🇨' },
  { code: '+20', country: 'Egypt', abbr: 'EG', flag: '🇪🇬' },
  { code: '+503', country: 'El Salvador', abbr: 'SV', flag: '🇸🇻' },
  { code: '+240', country: 'Equatorial Guinea', abbr: 'GQ', flag: '🇬🇶' },
  { code: '+291', country: 'Eritrea', abbr: 'ER', flag: '🇪🇷' },
  { code: '+372', country: 'Estonia', abbr: 'EE', flag: '🇪🇪' },
  { code: '+251', country: 'Ethiopia', abbr: 'ET', flag: '🇪🇹' },
  { code: '+679', country: 'Fiji', abbr: 'FJ', flag: '🇫🇯' },
  { code: '+358', country: 'Finland', abbr: 'FI', flag: '🇫🇮' },
  { code: '+33', country: 'France', abbr: 'FR', flag: '🇫🇷' },
  { code: '+241', country: 'Gabon', abbr: 'GA', flag: '🇬🇦' },
  { code: '+220', country: 'Gambia', abbr: 'GM', flag: '🇬🇲' },
  { code: '+995', country: 'Georgia', abbr: 'GE', flag: '🇬🇪' },
  { code: '+49', country: 'Germany', abbr: 'DE', flag: '🇩🇪' },
  { code: '+233', country: 'Ghana', abbr: 'GH', flag: '🇬🇭' },
  { code: '+30', country: 'Greece', abbr: 'GR', flag: '🇬🇷' },
  { code: '+502', country: 'Guatemala', abbr: 'GT', flag: '🇬🇹' },
  { code: '+224', country: 'Guinea', abbr: 'GN', flag: '🇬🇳' },
  { code: '+245', country: 'Guinea-Bissau', abbr: 'GW', flag: '🇬🇼' },
  { code: '+592', country: 'Guyana', abbr: 'GY', flag: '🇬🇾' },
  { code: '+509', country: 'Haiti', abbr: 'HT', flag: '🇭🇹' },
  { code: '+504', country: 'Honduras', abbr: 'HN', flag: '🇭🇳' },
  { code: '+852', country: 'Hong Kong', abbr: 'HK', flag: '🇭🇰' },
  { code: '+36', country: 'Hungary', abbr: 'HU', flag: '🇭🇺' },
  { code: '+354', country: 'Iceland', abbr: 'IS', flag: '🇮🇸' },
  { code: '+91', country: 'India', abbr: 'IN', flag: '🇮🇳' },
  { code: '+62', country: 'Indonesia', abbr: 'ID', flag: '🇮🇩' },
  { code: '+98', country: 'Iran', abbr: 'IR', flag: '🇮🇷' },
  { code: '+964', country: 'Iraq', abbr: 'IQ', flag: '🇮🇶' },
  { code: '+353', country: 'Ireland', abbr: 'IE', flag: '🇮🇪' },
  { code: '+972', country: 'Israel', abbr: 'IL', flag: '🇮🇱' },
  { code: '+39', country: 'Italy', abbr: 'IT', flag: '🇮🇹' },
  { code: '+225', country: 'Ivory Coast', abbr: 'CI', flag: '🇨🇮' },
  { code: '+81', country: 'Japan', abbr: 'JP', flag: '🇯🇵' },
  { code: '+962', country: 'Jordan', abbr: 'JO', flag: '🇯🇴' },
  { code: '+7', country: 'Kazakhstan', abbr: 'KZ', flag: '🇰🇿' },
  { code: '+254', country: 'Kenya', abbr: 'KE', flag: '🇰🇪' },
  { code: '+965', country: 'Kuwait', abbr: 'KW', flag: '🇰🇼' },
  { code: '+996', country: 'Kyrgyzstan', abbr: 'KG', flag: '🇰🇬' },
  { code: '+856', country: 'Laos', abbr: 'LA', flag: '🇱🇦' },
  { code: '+371', country: 'Latvia', abbr: 'LV', flag: '🇱🇻' },
  { code: '+961', country: 'Lebanon', abbr: 'LB', flag: '🇱🇧' },
  { code: '+266', country: 'Lesotho', abbr: 'LS', flag: '🇱🇸' },
  { code: '+231', country: 'Liberia', abbr: 'LR', flag: '🇱🇷' },
  { code: '+218', country: 'Libya', abbr: 'LY', flag: '🇱🇾' },
  { code: '+423', country: 'Liechtenstein', abbr: 'LI', flag: '🇱🇮' },
  { code: '+370', country: 'Lithuania', abbr: 'LT', flag: '🇱🇹' },
  { code: '+352', country: 'Luxembourg', abbr: 'LU', flag: '🇱🇺' },
  { code: '+853', country: 'Macau', abbr: 'MO', flag: '🇲🇴' },
  { code: '+389', country: 'Macedonia', abbr: 'MK', flag: '🇲🇰' },
  { code: '+261', country: 'Madagascar', abbr: 'MG', flag: '🇲🇬' },
  { code: '+265', country: 'Malawi', abbr: 'MW', flag: '🇲🇼' },
  { code: '+60', country: 'Malaysia', abbr: 'MY', flag: '🇲🇾' },
  { code: '+960', country: 'Maldives', abbr: 'MV', flag: '🇲🇻' },
  { code: '+223', country: 'Mali', abbr: 'ML', flag: '🇲🇱' },
  { code: '+356', country: 'Malta', abbr: 'MT', flag: '🇲🇹' },
  { code: '+222', country: 'Mauritania', abbr: 'MR', flag: '🇲🇷' },
  { code: '+230', country: 'Mauritius', abbr: 'MU', flag: '🇲🇺' },
  { code: '+52', country: 'Mexico', abbr: 'MX', flag: '🇲🇽' },
  { code: '+373', country: 'Moldova', abbr: 'MD', flag: '🇲🇩' },
  { code: '+377', country: 'Monaco', abbr: 'MC', flag: '🇲🇨' },
  { code: '+976', country: 'Mongolia', abbr: 'MN', flag: '🇲🇳' },
  { code: '+382', country: 'Montenegro', abbr: 'ME', flag: '🇲🇪' },
  { code: '+212', country: 'Morocco', abbr: 'MA', flag: '🇲🇦' },
  { code: '+258', country: 'Mozambique', abbr: 'MZ', flag: '🇲🇿' },
  { code: '+95', country: 'Myanmar', abbr: 'MM', flag: '🇲🇲' },
  { code: '+264', country: 'Namibia', abbr: 'NA', flag: '🇳🇦' },
  { code: '+977', country: 'Nepal', abbr: 'NP', flag: '🇳🇵' },
  { code: '+31', country: 'Netherlands', abbr: 'NL', flag: '🇳🇱' },
  { code: '+64', country: 'New Zealand', abbr: 'NZ', flag: '🇳🇿' },
  { code: '+505', country: 'Nicaragua', abbr: 'NI', flag: '🇳🇮' },
  { code: '+227', country: 'Niger', abbr: 'NE', flag: '🇳🇪' },
  { code: '+234', country: 'Nigeria', abbr: 'NG', flag: '🇳🇬' },
  { code: '+850', country: 'North Korea', abbr: 'KP', flag: '🇰🇵' },
  { code: '+47', country: 'Norway', abbr: 'NO', flag: '🇳🇴' },
  { code: '+968', country: 'Oman', abbr: 'OM', flag: '🇴🇲' },
  { code: '+92', country: 'Pakistan', abbr: 'PK', flag: '🇵🇰' },
  { code: '+507', country: 'Panama', abbr: 'PA', flag: '🇵🇦' },
  { code: '+675', country: 'Papua New Guinea', abbr: 'PG', flag: '🇵🇬' },
  { code: '+595', country: 'Paraguay', abbr: 'PY', flag: '🇵🇾' },
  { code: '+51', country: 'Peru', abbr: 'PE', flag: '🇵🇪' },
  { code: '+63', country: 'Philippines', abbr: 'PH', flag: '🇵🇭' },
  { code: '+48', country: 'Poland', abbr: 'PL', flag: '🇵🇱' },
  { code: '+351', country: 'Portugal', abbr: 'PT', flag: '🇵🇹' },
  { code: '+974', country: 'Qatar', abbr: 'QA', flag: '🇶🇦' },
  { code: '+40', country: 'Romania', abbr: 'RO', flag: '🇷🇴' },
  { code: '+7', country: 'Russia', abbr: 'RU', flag: '🇷🇺' },
  { code: '+250', country: 'Rwanda', abbr: 'RW', flag: '🇷🇼' },
  { code: '+966', country: 'Saudi Arabia', abbr: 'SA', flag: '🇸🇦' },
  { code: '+221', country: 'Senegal', abbr: 'SN', flag: '🇸🇳' },
  { code: '+381', country: 'Serbia', abbr: 'RS', flag: '🇷🇸' },
  { code: '+248', country: 'Seychelles', abbr: 'SC', flag: '🇸🇨' },
  { code: '+232', country: 'Sierra Leone', abbr: 'SL', flag: '🇸🇱' },
  { code: '+65', country: 'Singapore', abbr: 'SG', flag: '🇸🇬' },
  { code: '+421', country: 'Slovakia', abbr: 'SK', flag: '🇸🇰' },
  { code: '+386', country: 'Slovenia', abbr: 'SI', flag: '🇸🇮' },
  { code: '+252', country: 'Somalia', abbr: 'SO', flag: '🇸🇴' },
  { code: '+27', country: 'South Africa', abbr: 'ZA', flag: '🇿🇦' },
  { code: '+82', country: 'South Korea', abbr: 'KR', flag: '🇰🇷' },
  { code: '+211', country: 'South Sudan', abbr: 'SS', flag: '🇸🇸' },
  { code: '+34', country: 'Spain', abbr: 'ES', flag: '🇪🇸' },
  { code: '+94', country: 'Sri Lanka', abbr: 'LK', flag: '🇱🇰' },
  { code: '+249', country: 'Sudan', abbr: 'SD', flag: '🇸🇩' },
  { code: '+597', country: 'Suriname', abbr: 'SR', flag: '🇸🇷' },
  { code: '+268', country: 'Swaziland', abbr: 'SZ', flag: '🇸🇿' },
  { code: '+46', country: 'Sweden', abbr: 'SE', flag: '🇸🇪' },
  { code: '+41', country: 'Switzerland', abbr: 'CH', flag: '🇨🇭' },
  { code: '+963', country: 'Syria', abbr: 'SY', flag: '🇸🇾' },
  { code: '+886', country: 'Taiwan', abbr: 'TW', flag: '🇹🇼' },
  { code: '+992', country: 'Tajikistan', abbr: 'TJ', flag: '🇹🇯' },
  { code: '+255', country: 'Tanzania', abbr: 'TZ', flag: '🇹🇿' },
  { code: '+66', country: 'Thailand', abbr: 'TH', flag: '🇹🇭' },
  { code: '+228', country: 'Togo', abbr: 'TG', flag: '🇹🇬' },
  { code: '+676', country: 'Tonga', abbr: 'TO', flag: '🇹🇴' },
  { code: '+216', country: 'Tunisia', abbr: 'TN', flag: '🇹🇳' },
  { code: '+90', country: 'Turkey', abbr: 'TR', flag: '🇹🇷' },
  { code: '+993', country: 'Turkmenistan', abbr: 'TM', flag: '🇹🇲' },
  { code: '+256', country: 'Uganda', abbr: 'UG', flag: '🇺🇬' },
  { code: '+380', country: 'Ukraine', abbr: 'UA', flag: '🇺🇦' },
  { code: '+971', country: 'United Arab Emirates', abbr: 'AE', flag: '🇦🇪' },
  { code: '+44', country: 'United Kingdom', abbr: 'GB', flag: '🇬🇧' },
  { code: '+598', country: 'Uruguay', abbr: 'UY', flag: '🇺🇾' },
  { code: '+998', country: 'Uzbekistan', abbr: 'UZ', flag: '🇺🇿' },
  { code: '+678', country: 'Vanuatu', abbr: 'VU', flag: '🇻🇺' },
  { code: '+58', country: 'Venezuela', abbr: 'VE', flag: '🇻🇪' },
  { code: '+84', country: 'Vietnam', abbr: 'VN', flag: '🇻🇳' },
  { code: '+967', country: 'Yemen', abbr: 'YE', flag: '🇾🇪' },
  { code: '+260', country: 'Zambia', abbr: 'ZM', flag: '🇿🇲' },
  { code: '+263', country: 'Zimbabwe', abbr: 'ZW', flag: '🇿🇼' },
]
