-- Insert 10 sample candidates into the candidates table

INSERT INTO candidates (
  id,
  name,
  email,
  mobile_number,
  current_location,
  preferred_location,
  industry,
  years_of_experience,
  current_ctc,
  expected_ctc,
  notice_period,
  skills,
  status,
  feedback,
  cv_url,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'Rajesh Kumar',
  'rajesh.kumar@email.com',
  '+91-9876543210',
  'Bangalore',
  'Bangalore, Hyderabad',
  'Information Technology',
  5.5,
  '12 LPA',
  '18 LPA',
  '30 days',
  'React, Node.js, TypeScript, AWS, MongoDB, Docker',
  'Under Review',
  'Strong technical skills. Good communication during initial screening.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Priya Sharma',
  'priya.sharma@email.com',
  '+91-9876543211',
  'Mumbai',
  'Mumbai, Pune',
  'Finance',
  8.0,
  '15 LPA',
  '22 LPA',
  '60 days',
  'Financial Analysis, Excel, SAP, Power BI, Risk Management',
  'Shortlisted',
  'Excellent analytical skills. CPA certified. Great fit for senior analyst role.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Amit Patel',
  'amit.patel@email.com',
  '+91-9876543212',
  'Ahmedabad',
  'Ahmedabad, Mumbai',
  'Manufacturing',
  12.0,
  '25 LPA',
  '30 LPA',
  'Immediate',
  'Operations Management, Six Sigma, Lean Manufacturing, Supply Chain',
  'Interview Scheduled',
  'Extensive experience in manufacturing operations. Currently available for immediate joining.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Sneha Reddy',
  'sneha.reddy@email.com',
  '+91-9876543213',
  'Hyderabad',
  'Hyderabad, Chennai',
  'Healthcare',
  6.5,
  '10 LPA',
  '14 LPA',
  '30 days',
  'Medical Coding, ICD-10, Healthcare Analytics, EMR Systems',
  'New',
  NULL,
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Vikram Singh',
  'vikram.singh@email.com',
  '+91-9876543214',
  'Delhi',
  'Delhi NCR',
  'Information Technology',
  10.0,
  '28 LPA',
  '35 LPA',
  '90 days',
  'Python, Machine Learning, AI, TensorFlow, Data Science, SQL',
  'Shortlisted',
  'PhD in Computer Science. Published researcher in ML/AI. Looking for leadership roles.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Kavya Menon',
  'kavya.menon@email.com',
  '+91-9876543215',
  'Kochi',
  'Kochi, Bangalore',
  'Marketing',
  4.0,
  '8 LPA',
  '12 LPA',
  '45 days',
  'Digital Marketing, SEO, SEM, Google Analytics, Content Strategy, Social Media',
  'Under Review',
  'Creative portfolio. Strong background in B2B marketing. References checked.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Arjun Nair',
  'arjun.nair@email.com',
  '+91-9876543216',
  'Chennai',
  'Chennai, Bangalore',
  'Automotive',
  15.0,
  '32 LPA',
  '40 LPA',
  '60 days',
  'Automotive Engineering, CAD/CAM, Project Management, ISO Standards',
  'Rejected',
  'Overqualified for the position. Salary expectations too high for budget.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Divya Iyer',
  'divya.iyer@email.com',
  '+91-9876543217',
  'Pune',
  'Pune, Mumbai',
  'Human Resources',
  7.0,
  '14 LPA',
  '18 LPA',
  '30 days',
  'Talent Acquisition, HRIS, Employee Relations, Compensation & Benefits',
  'Interview Scheduled',
  'SHRM certified. Experience with global recruitment. Second round scheduled for next week.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Rohit Verma',
  'rohit.verma@email.com',
  '+91-9876543218',
  'Jaipur',
  'Jaipur, Delhi',
  'Retail',
  3.5,
  '6 LPA',
  '9 LPA',
  '15 days',
  'Retail Operations, Inventory Management, Customer Service, POS Systems',
  'New',
  NULL,
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Ananya Das',
  'ananya.das@email.com',
  '+91-9876543219',
  'Kolkata',
  'Kolkata, Bangalore',
  'Education',
  9.0,
  '16 LPA',
  '20 LPA',
  '45 days',
  'Curriculum Development, EdTech, Learning Management Systems, Training',
  'Shortlisted',
  'M.Ed from prestigious university. Experience with online learning platforms. Very impressive interview.',
  'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  NOW(),
  NOW()
);
