-- Seed 15 matching candidate profiles for Technical Support position
-- First, get the JobKarle organization ID (we'll use a variable)

-- Insert 15 technical support candidates
INSERT INTO candidates (
  name, 
  email, 
  mobile_number, 
  current_location, 
  preferred_location,
  skills, 
  industry,
  years_of_experience,
  current_ctc,
  expected_ctc,
  notice_period,
  status,
  organization_id,
  created_at,
  updated_at
) VALUES
-- Candidate 1
(
  'Rajesh Kumar',
  'rajesh.kumar@email.com',
  '+91 9876543210',
  'Bengaluru',
  'Bengaluru',
  'Technical Support, Troubleshooting, Customer Service, Windows, Linux, Network Support, Remote Desktop, Ticketing Systems, ITIL',
  'IT Services',
  3.5,
  '4,00,000',
  '5,50,000',
  '30 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 2
(
  'Priya Sharma',
  'priya.sharma@email.com',
  '+91 9876543211',
  'Bengaluru',
  'Bengaluru, Hyderabad',
  'Help Desk Support, Technical Documentation, Hardware Troubleshooting, Software Installation, Active Directory, Email Support, Microsoft Office, Windows 10/11',
  'Technology',
  2.5,
  '3,50,000',
  '4,80,000',
  '15 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 3
(
  'Amit Patel',
  'amit.patel@email.com',
  '+91 9876543212',
  'Bengaluru',
  'Bengaluru',
  'IT Support, Desktop Support, Network Troubleshooting, VPN Configuration, Printer Setup, Remote Support Tools, ServiceNow, Windows Server',
  'Information Technology',
  4.0,
  '5,00,000',
  '6,50,000',
  '60 days',
  'ringing',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 4
(
  'Sneha Reddy',
  'sneha.reddy@email.com',
  '+91 9876543213',
  'Hyderabad',
  'Bengaluru, Hyderabad',
  'Technical Support Engineer, Customer Support, Issue Resolution, System Administration, Cloud Support, AWS Basics, Linux Commands, SQL Basics',
  'IT & Software',
  3.0,
  '4,20,000',
  '5,80,000',
  '30 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 5
(
  'Vikram Singh',
  'vikram.singh@email.com',
  '+91 9876543214',
  'Bengaluru',
  'Bengaluru',
  'L1 Support, L2 Support, Incident Management, Problem Management, JIRA, Zendesk, Customer Communication, Technical Writing',
  'IT Services',
  2.0,
  '3,00,000',
  '4,50,000',
  'Immediate',
  'linedup',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 6
(
  'Kavya Iyer',
  'kavya.iyer@email.com',
  '+91 9876543215',
  'Bengaluru',
  'Bengaluru, Chennai',
  'Application Support, Database Support, Log Analysis, Performance Monitoring, Shell Scripting, Python Basics, MySQL, PostgreSQL',
  'Software',
  3.5,
  '4,80,000',
  '6,20,000',
  '45 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 7
(
  'Arjun Nair',
  'arjun.nair@email.com',
  '+91 9876543216',
  'Chennai',
  'Bengaluru, Chennai',
  'IT Support Specialist, Hardware Maintenance, Software Troubleshooting, Network Configuration, Cisco Basics, Active Directory, Group Policy, Exchange Server',
  'Technology',
  4.5,
  '5,50,000',
  '7,00,000',
  '60 days',
  'ringing',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 8
(
  'Divya Menon',
  'divya.menon@email.com',
  '+91 9876543217',
  'Bengaluru',
  'Bengaluru',
  'Technical Support, Customer Service, Ticketing Systems, Remote Desktop Support, Windows OS, Mac OS, Mobile Device Support, O365 Administration',
  'IT Services',
  2.5,
  '3,80,000',
  '5,20,000',
  '30 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 9
(
  'Karthik Krishnan',
  'karthik.krishnan@email.com',
  '+91 9876543218',
  'Pune',
  'Bengaluru, Pune, Mumbai',
  'Help Desk, Desktop Support, Laptop Configuration, Antivirus Management, Backup Solutions, VPN Support, Zoom Support, Microsoft Teams',
  'Information Technology',
  3.0,
  '4,00,000',
  '5,50,000',
  '30 days',
  'linedup',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 10
(
  'Meera Bhat',
  'meera.bhat@email.com',
  '+91 9876543219',
  'Bengaluru',
  'Bengaluru',
  'Technical Support Engineer, System Monitoring, Incident Response, Root Cause Analysis, Documentation, Knowledge Base Management, Confluence, Slack',
  'IT & Technology',
  4.0,
  '5,20,000',
  '6,80,000',
  '45 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 11
(
  'Ravi Verma',
  'ravi.verma@email.com',
  '+91 9876543220',
  'Delhi',
  'Bengaluru, Delhi, Gurgaon',
  'IT Support, Network Support, Firewall Configuration, Router Setup, Switch Configuration, TCP/IP, DNS, DHCP, LAN/WAN',
  'Networking',
  3.5,
  '4,50,000',
  '6,00,000',
  '60 days',
  'ringing',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 12
(
  'Anjali Desai',
  'anjali.desai@email.com',
  '+91 9876543221',
  'Mumbai',
  'Bengaluru, Mumbai, Pune',
  'Application Support, Web Application Troubleshooting, API Testing, Postman, Browser DevTools, HTML/CSS Basics, JavaScript Basics, REST APIs',
  'Software Services',
  2.5,
  '3,60,000',
  '5,00,000',
  '30 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 13
(
  'Suresh Babu',
  'suresh.babu@email.com',
  '+91 9876543222',
  'Bengaluru',
  'Bengaluru',
  'Technical Support, Cloud Support, Azure Basics, AWS EC2, S3 Storage, Virtual Machines, Cloud Backup, SaaS Support, IaaS Support',
  'Cloud Services',
  3.0,
  '4,40,000',
  '5,90,000',
  '30 days',
  'linedup',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 14
(
  'Pooja Agarwal',
  'pooja.agarwal@email.com',
  '+91 9876543223',
  'Bengaluru',
  'Bengaluru, Hyderabad',
  'L1/L2 Support, IT Infrastructure Support, Server Monitoring, Disk Space Management, User Account Management, Patch Management, Antivirus Updates, Backup Monitoring',
  'IT Infrastructure',
  4.5,
  '5,80,000',
  '7,50,000',
  '45 days',
  'shortlisted',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
),
-- Candidate 15
(
  'Arun Kumar',
  'arun.kumar@email.com',
  '+91 9876543224',
  'Kochi',
  'Bengaluru, Kochi, Chennai',
  'Technical Support Specialist, Help Desk Management, Team Coordination, Training & Onboarding, Process Documentation, Quality Assurance, Customer Satisfaction, Escalation Handling',
  'IT Services',
  5.0,
  '6,00,000',
  '8,00,000',
  '60 days',
  'ringing',
  (SELECT id FROM organization WHERE email = 'hr@jobkarle.com' LIMIT 1),
  NOW(),
  NOW()
);

-- Output success message
SELECT 'Successfully inserted 15 technical support candidates' AS result;
